### PR TITLE
libcameraservice: Fixup camera package name additions for 14.0 QPR2

### PR DESCRIPTION
**Pull request by Terminator-J**
- Fixes build-time linking when utilizing build flags to support MIUI and OnePlus prebuilt camera apks

- Replace usage of String8() with c_str()

_____

Please let me know if this breaks anything on devices that don't use any custom client package names / client info lib build flags.

### CODE REVIEW

**Review by neobuddy89 — CHANGES_REQUESTED** [review]
Why do you need defaults defined in cameraserver? Remove it.

**Comment by Terminator-J** [comment]
> Why do you need defaults defined in cameraserver? Remove it.

Without defaults added to cameraserver Android.bp, build fails with linker error when using TARGET_CAMERA_NEEDS_CLIENT_INFO_LIB BoardConfig flag:

[error.log](https://github.com/crdroidandroid/android_frameworks_av/files/15006504/error.log)

**Comment by ShevT** [comment]
> > Why do you need defaults defined in cameraserver? Remove it.
> 
> Without defaults added to cameraserver Android.bp, build fails with linker error when using TARGET_CAMERA_NEEDS_CLIENT_INFO_LIB BoardConfig flag:
> 
> [error.log](https://github.com/crdroidandroid/android_frameworks_av/files/15006504/error.log)

It's not needed here:
https://github.com/crdroidandroid/android_frameworks_av/pull/42/commits/6c98bb738276dea21fc512644d378e86680effe9#diff-d9547f241cc641de397ba0caa253bebf891f4d2ef5953c424fc2260b30cf9250R31-R33

**Comment by ShevT** [comment]
> > Why do you need defaults defined in cameraserver? Remove it.
> 
> Without defaults added to cameraserver Android.bp, build fails with linker error when using TARGET_CAMERA_NEEDS_CLIENT_INFO_LIB BoardConfig flag:
> 
> [error.log](https://github.com/crdroidandroid/android_frameworks_av/files/15006504/error.log)

Everything you need is already here - https://github.com/crdroidandroid/android_frameworks_av/blob/14.0/services/camera/libcameraservice/Android.bp#L124-L126

**Comment by Terminator-J** [comment]
Long story short, the modified commit that @neobuddy89 used doesn't actually fix compiling the ROM when `TARGET_CAMERA_NEEDS_CLIENT_INFO_LIB` flag is set in BoardConfig after QPR2 merge.

It used to be sufficient to have defaults in `services/camera/libcameraservice/Android.bp`.
It's no longer sufficient.
Without adding them to `camera/cameraserver/Android.bp`, then ROM compilation fails with the attached linker error.
[error.log](https://github.com/crdroidandroid/android_frameworks_av/files/15135091/error.log)

Does adding the defaults like in my original commit here cause problems for other devices?

**Pull request closed without merging**
