### PR TITLE
mediaplayer: Fix constructor calling sequence

### PR DESCRIPTION
**Pull request by Laker87**

### CODE REVIEW

**Comment by gwolf2u** [comment]
this still needed?

**Comment by Laker87** [comment]
> this still needed?

Yes. Without this commit prebuilt libcameraservice does not work on Xiaomi devices.

**Review by neobuddy89 — APPROVED** [review]

**Comment by neobuddy89** [comment]
Just FYI:
On some of our Xiaomi devices, we switched to source-built libcameraservice along with below commit
https://github.com/crdroidandroid/android_device_xiaomi_phoenix/commit/4cc00906d5ac09dff02e44cb64401f62e7ac61d5

and portrait mode works.

**Comment by Laker87** [comment]
> Just FYI:
> On some of our Xiaomi devices, we switched to source-built libcameraservice along with below commit
> https://github.com/crdroidandroid/android_device_xiaomi_phoenix/commit/4cc00906d5ac09dff02e44cb64401f62e7ac61d5
> 
> and portrait mode works.

We use prebuilt libcameraservice for anx/miui camera.  This camera doesn't work with oss libcameraservice and camera provider

**Pull request merged**
