### PR TITLE
fix build error

### PR DESCRIPTION
**Pull request by officialyash007**
frameworks/av/camera/cameraserver/main_cameraserver.cpp:20:10: fatal error: 'CameraService.h' file not found #include "CameraService.h"

### CODE REVIEW

**Comment by gwolf2u** [comment]
does this happen for specific device as I didn't had the issue?

**Comment by officialyash007** [comment]
> does this happen for specific device as I didn't had the issue?

Yes for violet

**Comment by neobuddy89** [comment]
This would break cameraservice for other devices by default, right?

**Comment by neobuddy89** [comment]
cameraservice.h is guarded as below
#ifdef NO_CAMERA_SERVER
#include "CameraService.h"
#include <hidl/HidlTransportSupport.h>
#endif

Find out how can you activate NO_CAMERA_SERVER

Hint: Look in vendor/lineage maybe??

**Comment by officialyash007** [comment]
> This would break cameraservice for other devices by default, right?

This will fix that for other devices
https://github.com/SuperiorOS/android_vendor_superior/commit/b0e3f6996dcfd7bba4708a4a349c2c0e9680d745

**Pull request closed without merging**
