### PR TITLE
codec2 sfplugin: add traces for frame processing latency

### PR DESCRIPTION
**Pull request by ShevT**
Bug: 217969867
Test: Record trace & analyze in ui.perfetto.dev
Change-Id: Ideccc5e78ed5fcd2744b33c6036b5afa231b2b9a

### CODE REVIEW

**Comment by neobuddy89** [comment]
Traces? Who read them?

**Comment by ShevT** [comment]
https://android-review.googlesource.com/c/platform/frameworks/av/+/2043051

**Comment by neobuddy89** [comment]
Let AOSP merge then. Doesn't seem to be of any use now.

**Comment by ShevT** [comment]
Merged

**Comment by neobuddy89** [comment]
In next AOSP release.

**Pull request closed without merging**
